### ISSUE TITLE
Is it possible to use UnifiedNlp on new Samsung phone?

### ISSUE THREAD

**Issue by Extarys** [microg/android_packages_apps_UnifiedNlp#176]
I bought an A70 and I would like to know if it's possible to use Mozilla Location Services alongside GAPPS. I couldn't find any info on this.

It seems that there is no root method right now as the phone is too new.

Thanks!

EDIT with more details:

UnifiedNlp (noGAPPS) is marked as already installed (v 17.7.85) in Fdroid
I tried installing the GAPPS version, but since I'm on the Samsung firmware, there is no Xposed modules I can run and the app tells me UnifiedNlp is not binded to the system.

:cry:

**Comment by IzzySoft** [comment]
> UnifiedNlp (noGAPPS) is marked as already installed (v 17.7.85) in Fdroid

That is because you have GApps installed, which uses the same package name (that's how microG works, being a "drop-in replacement" for GApps). You will need the GApps version – or install a custom ROM without GApps and add microG Core. Or pick [LinageOS for microG](https://lineage.microg.org/) as your custom ROM to start with (it it's available for your device), and have it already "baked in" – including MLS.

> but since I'm on the Samsung firmware, there is no Xposed modules I can run and the app tells me UnifiedNlp is not binded to the system.

Then you're out of luck. If your stock ROM doesn't support non-Google geolocation providers, you need to "trick the system", which is done via Xposed. Which requires your bootloader to be unlocked so the framework can be flashed. As I have no Samsung devices, I've no idea how that works with them – so this is all I can give as an answer.

**Comment by Extarys** [comment]
Thanks, at least now I understand how this works. :smile: 

I'll wait until XDA devs find ways into the A70.
