### ISSUE TITLE
[req] ui for stats

### ISSUE THREAD

**Issue by TameOfGroans** [microg/android_packages_apps_UnifiedNlp#29]
locally or Lan Web interface

spiffy charts and stats

**Comment by mar-v-in** [comment]
What kind of stats do you mean. Currently UnifiedNlp is not collecting storing any data other than the configuration

**Comment by TameOfGroans** [comment]
Points of data

# towers
# unique mac addr 
# triangulation instances 

I appreciate being corrected. I had though UnifiedNLP would need to offer a feature before NLP providers [sic] could offer/produce.

**Comment by TameOfGroans** [comment]
oh, pound sign is markup.  oops

**Comment by n76** [comment]
Those will vary with backends.

At present the two backends that I wrote have minimal statistical data they display but I can see that adding stats appropriate to each backend would be nice.

FWIW, prior to Android 5.0 the mobil cell tower and WiFi (wlan) APIs do not support getting timing information, so estimating distance to a transmitter is not really possible. So your network based location is more of a mash of the coverage areas of the detected transmitters rather than triangulation or trilateration. And that goes for the collection of data used by open source projects to estimate mobile cell tower and WiFi AP locations, so the transmitter locations are not as accurate as one might like. Once 5.1 and later Android systems become wide spread and the collection software is updated to acquire the timing data as a range estimate this should improve.

Also FWIW many Android phones, with Samsung being a prime example, only report one mobile cell tower (the one the phone is connected to) even though the APIs have allowed reporting of all towers seen for some time now. So trilateration or triangulation using mobile cell tower data alone is not possible on many phones.

**Comment by mar-v-in** [comment]
I guess most interesting data and stats are inside the backends. Stats like which application uses location is already monitored by the system since Android 4.4 (or alike). 

Will close this issue here. If you want a specific backend to contain some stats, create an issue within the corresponding issue page.
