### ISSUE TITLE
java.lang.SecurityException: Not allowed to start service Intent without permission com.google.android.c2dm.permission.RECEIVE

### ISSUE THREAD

**Issue by agilob** [microg/android_packages_apps_UnifiedNlp#87]
```
java.lang.SecurityException: Not allowed to start service Intent { 
act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) }
without permission
com.google.android.c2dm.permission.RECEIVE
at android.app.ContextImpl.startService(ContextImpl.java:1217)
at android.content.ContextWrapper.startService(ContextWrapper.java:383)
at org.microg.gms.gcm.PushRegisterProxy.onHandleIntent(PushRegisterProxy.java:32)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.os.HandlerThread.run(HandlerThread.java:60)
```
Same device, android 4.1.2 LG, stock ROM.

**Comment by mar-v-in** [comment]
1. You are using microG GmsCore. Issues with GmsCore should be reported in its issue tracker: https://github.com/microg/android_packages_apps_GmsCore/issues
2. This happens when you installed an application that uses GCM before you installed GmsCore. Android was not able to grant the requires permission to the app because it did not know about the permission at all (because it is defined in GmsCore). To work around this issue you can re-install the app that causes the problem (no need to remove it, just install it again).

**Comment by agilob** [comment]
Thanks for the explanation. How can I identify those apps?

**Comment by mar-v-in** [comment]
In your case it seems to be the GsfProxy app. It depends on the app how or if at all it displays the exception in logcat.

**Comment by HanteIsHante** [comment]
I have encountered the same problem, but what does this have to do with GmsCore?
Question URL https://github.com/HanteIsHante/file/issues/62

**Comment by ale5000-git** [comment]
@HanteIsHante

This error is related to GCM (C2DM is the old version of GCM), it is a "function" not included in UnifiedNlp but included in GmsCore (it possible also need GsfProxy).

So if you are using UnifiedNlp, then the app will never work.
You have to use GmsCore (GmsCore also include all things included in UnifiedNlp but they aren't needed in this specific case).
